'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createAdminMonitoring,clientView}=require('../admin-monitoring-service');
function fixture({badDatabase=false,badFeed=false,badClients=false,stale15=false,clientState='READY',delivery={failed:0,pending:0,delayed:0},queue={failed:0,delayed:0}}={}){
 const now=Date.now(),calls={clients:0};
 const pool={query:async q=>{if(badDatabase)throw new Error('password=PRIVATE_TEST_SECRET');if(q.text.includes('telegram_deliveries'))return {rows:[delivery]};if(q.text.includes('autotrade_commands'))return {rows:[queue]};return {rows:[{alive:1}]};}};
 const deps={auth:{ready:true,store:{pool},service:{adminClients:async()=>{calls.clients++;if(badClients)throw new Error('PRIVATE_TEST_SECRET');return [{id:'u',displayName:'Client',email:'client@test',ibName:'IB'}];}}},trading:{enabled:true,ready:true,dispatchLastSuccessAt:now,service:{connectionMonitor:async()=>({transport:'EA_LOCAL',accountMask:'***1234',serverMask:'Demo',tradeMode:'REAL',connectorVersion:'1.3.0-ea-local',lastSeenAt:now,connection:{online:true,ready:clientState==='READY',state:clientState,password:'PRIVATE_TEST_SECRET'},permissions:{terminal:true,account:true,expert:clientState==='READY'},control:{desiredState:'RUNNING',effectiveState:'RUNNING',lastError:'PRIVATE_TEST_SECRET'},secret:'PRIVATE_TEST_SECRET'})},store:{getHostedWorkerPoolOverview:async()=>({hosts:[],totals:{waiting:0}})}},telegram:()=>({ready:true,token:'PRIVATE_TEST_SECRET'}),hostedEnabled:false,fetchMarkets:async()=>{if(badFeed)throw new Error('PRIVATE_TEST_SECRET');return [2,15].map(tf=>({symbol:'XAUUSD',timeframe:String(tf),strategyNormal:{tf:tf+'m'},receivedAt:now,signalObservedAt:stale15&&tf===15?now-120000:now}));}};
 return {monitor:createAdminMonitoring(deps),calls,deps};
}
test('only admin can monitor; authorization checked before shared cache',async()=>{const {monitor,calls}=fixture();await assert.rejects(monitor.snapshot({role:'ib'}),{code:'FORBIDDEN'});assert.equal(calls.clients,0);await monitor.snapshot({role:'admin'});await assert.rejects(monitor.snapshot({role:'client'}),{code:'FORBIDDEN'});});
test('all monitored paths return safe metadata; repeat requests coalesce',async()=>{const {monitor,calls}=fixture();const [a,b]=await Promise.all([monitor.snapshot({role:'admin'}),monitor.snapshot({role:'admin'})]);assert.equal(a,b);assert.equal(calls.clients,1);assert.equal(a.overall,'OK');assert.equal(a.summary.ready,1);assert.equal(a.accounts[0].tradeMode,'REAL');assert.equal(JSON.stringify(a).includes('PRIVATE_TEST_SECRET'),false);});
test('TF15 source freshness is independent from fresh TF2 / transport',async()=>{const {monitor}=fixture({stale15:true});const a=await monitor.snapshot({role:'admin'});assert.equal(a.components.find(c=>c.id==='feed2').status,'OK');assert.equal(a.components.find(c=>c.id==='feed15').status,'ERROR');assert.equal(a.overall,'ERROR');});
test('failures produce partial UNKNOWN / ERROR without leaking raw errors',async()=>{const {monitor}=fixture({badDatabase:true,badFeed:true,badClients:true});const a=await monitor.snapshot({role:'admin'});assert.equal(a.overall,'ERROR');assert.equal(a.clientsAvailable,false);assert.equal(a.components.find(c=>c.id==='database').status,'ERROR');assert.equal(a.components.find(c=>c.id==='feed2').status,'UNKNOWN');assert.equal(JSON.stringify(a).includes('PRIVATE_TEST_SECRET'),false);});
test('MT5 permission failures, delivery failures and stuck commands locate components',async()=>{const {monitor}=fixture({clientState:'CHECK_MT5',delivery:{failed:1,pending:2,delayed:1},queue:{delayed:1,failed:0}});const a=await monitor.snapshot({role:'admin'});for(const id of ['clients','telegram','orders'])assert.equal(a.components.find(c=>c.id===id).status,'WARNING');assert.ok(a.alerts.some(a=>a.userId==='u'&&a.component==='Client → MT5'));});
test('missing / future / stale heartbeats never claim online; unlinked is not a client error',()=>{const now=Date.now(),r={transport:'EA_LOCAL',connection:{online:true,ready:true,state:'READY'},client:{}};for(const t of [null,now+10000,now-31000]){const a=clientView({...r,lastSeenAt:t},now);assert.equal(a.online,false);assert.equal(a.ready,false);assert.equal(a.state,'OFFLINE');}assert.equal(clientView({...r,transport:'NOT_LINKED'},now).state,'NOT_LINKED');});
test('dispatcher stops updating health after 30 seconds; server uptime cannot conceal it',async()=>{const {monitor,deps}=fixture();deps.trading.dispatchLastSuccessAt=Date.now()-31000;const a=await monitor.snapshot({role:'admin'});assert.equal(a.components.find(c=>c.id==='trading').status,'ERROR');assert.equal(a.overall,'ERROR');});

test('admin sees pending webhook authentication without exposing the secret',async()=>{const {deps}=fixture();deps.webhook={enforced:false,secret:'PRIVATE_TEST_SECRET'};const a=await createAdminMonitoring(deps).snapshot({role:'admin'});assert.equal(a.components.find(c=>c.id==='webhook').status,'WARNING');assert.equal(JSON.stringify(a).includes('PRIVATE_TEST_SECRET'),false);deps.webhook.enforced=true;const b=await createAdminMonitoring(deps).snapshot({role:'admin'});assert.equal(b.components.find(c=>c.id==='webhook').status,'OK');});
