const test=require('node:test'),assert=require('node:assert/strict'),Core=require('../auto-trade-core');
const {evaluateEntrySop}=require('../normal-entry-sop');
const {MemoryAutoTradeStore}=require('../auto-trade-store');const {createAutoTradeService}=require('../auto-trade-service');
const config=()=>({capitalUsd:100,lotPerLayer:.01,layers:1,symbols:['XAUUSD'],strategyMode:'BOTH',modeSettings:{TF2_SCALPING:{gold:{enabled:true,lotPerLayer:.01,layers:3},fx:{enabled:false}},TF15_INTRA:{gold:{enabled:true,lotPerLayer:.02,layers:4},fx:{enabled:false}}}});
function market(tf){const r={fast:102,slow:101},d={symbol:'XAUUSD',timeframe:tf,normal3Side:'BUY',normal3Atr:1,normal3PricePastEntry:true,normal3Entry:100,normal3Close:100.5,normal3Solid:true,normal3Sop1:true,normal3Sop2:true,normal3Sop3:true,normal3Sop4:true,normal3Forecast:'BULLISH',normal3MarketPower:70,hemaConfirmation:{version:tf==='2'?'HEMA23_LIVE_V1':'HEMA1530_V1',['tf'+tf]:r,['tf'+(tf==='2'?'3':'30')]:r}};const x=evaluateEntrySop(d,tf),at=Date.now();return {symbol:'XAUUSD',timeframe:tf,receivedAt:at,signalObservedAt:at,strategyNormal:{tf:tf+'m',state:x.standardReady?'READY':'WATCH',side:x.side,solid:x.solid,entrySopVersion:x.version,sop:{gates:x.gates,sopGreen:x.green,forecast:x.forecast,marketPower:x.power,['hema'+tf]:x['hema'+tf],['hema'+(tf==='2'?'3':'30')]:x['hema'+(tf==='2'?'3':'30')]},plan:{entry:100,sl:98,tp1:102,tp2:104,tp3:106}}};}
test('two TFs use their independent lot and configurable layers',()=>{const c=Core.validateSettings(config());assert.equal(c.ok,true);for(const [tf,lot,layers] of [['2',.01,3],['15',.02,4]]){const cmd=Core.buildSetupCommand(market(tf),c.value);assert.ok(cmd);assert.equal(cmd.payload.lotPerLayer,lot);assert.equal(cmd.payload.layers,layers);}});
test('empty or explicitly disabled TF cannot fall back to global lot / layer; other TF still enters',()=>{for(const mode of ['TF2_SCALPING','TF15_INTRA'])for(const fields of [{enabled:false},{lotPerLayer:'',layers:2},{lotPerLayer:.01,layers:''},{lotPerLayer:null,layers:2}]){const c=config();c.modeSettings[mode].gold=fields;const v=Core.validateSettings(c);assert.equal(v.ok,true);assert.equal(Core.buildSetupCommand(market(mode==='TF2_SCALPING'?'2':'15'),v.value),null);assert.ok(Core.buildSetupCommand(market(mode==='TF2_SCALPING'?'15':'2'),v.value));}});
test('both empty saves without entry; invalid nonempty input is rejected',()=>{const c=config();for(const m of Object.values(c.modeSettings))m.gold={enabled:false};assert.equal(Core.validateSettings(c).ok,true);for(const tf of ['2','15'])assert.equal(Core.buildSetupCommand(market(tf),c),null);for(const layers of [0,11,1.5]){const d=config();d.modeSettings.TF15_INTRA.gold.layers=layers;assert.equal(Core.validateSettings(d).ok,false);}});
test('blank mode and its state persist without being revived by normalization',async()=>{const store=new MemoryAutoTradeStore();const c=config();c.modeSettings.TF15_INTRA.gold={enabled:false};const v=Core.validateSettings(c).value;await store.saveSettings('u',v);const saved=await store.getProfile('u');const again=Core.validateSettings(saved);assert.equal(again.ok,true);assert.equal(again.value.modeSettings.TF15_INTRA.gold.enabled,false);assert.equal(Core.effectiveSettings({...again.value,strategyMode:'TF15_INTRA'}).lotPerLayer,null);});
test('server revokes a previously delivered entry after its TF is disabled',async()=>{const store=new MemoryAutoTradeStore(),service=createAutoTradeService({store,allowDemoExecution:true,commandSigningKey:'test-signing-key-at-least-thirty-two-bytes'}),linked=await service.connectLocalEa('u');const c=config();c.modeSettings.TF15_INTRA.gold={enabled:false};await store.saveSettings('u',Core.validateSettings(c).value);await store.createCommand({id:'00000000-0000-4000-8000-000000000001',userId:'u',podId:linked.podId,type:'PLACE_SETUP',payload:{strategyMode:'TF15_INTRA'},expiresAt:Date.now()+30000,signature:'x',signedEnvelope:'x'});const result=await service.nextCommand(linked.podToken);assert.equal(result.command,null);});
