(function(){
  'use strict';
  const css=`
  .perf8{margin-top:10px;border:1px solid #27394f;background:linear-gradient(180deg,#0a111b,#060a10);border-radius:16px;padding:12px}.perf8-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.perf8-title{font-size:13px;font-weight:950;letter-spacing:.4px}.perf8-sub{font-size:9px;color:#8295ad;line-height:1.45;margin-top:3px}.perf8-badge{font-size:9px;border:1px solid #32e38d44;color:#69efaa;border-radius:999px;padding:5px 8px;white-space:nowrap}.perf8-kpis{display:grid;grid-template-columns:repeat(8,1fr);gap:7px}.perf8-kpi{padding:10px;border:1px solid #1b293a;background:#080e16;border-radius:10px;min-width:0}.perf8-kpi span{display:block;font-size:8px;color:#7489a2;text-transform:uppercase;letter-spacing:.45px}.perf8-kpi b{display:block;font-size:16px;margin-top:4px}.perf8-kpi small{display:block;font-size:8px;color:#6e8299;margin-top:3px;line-height:1.3}.perf8-good{color:#32e38d}.perf8-bad{color:#ff6070}.perf8-warn{color:#ffb74b}.perf8-blue{color:#51a8ff}.perf8-tabs{display:flex;gap:6px;margin:10px 0 8px;flex-wrap:wrap}.perf8-tab{border:1px solid #213147;background:#0a111b;color:#95a8c0;border-radius:8px;padding:7px 10px;font-size:9px;font-weight:800;cursor:pointer}.perf8-tab.active{color:#fff;border-color:#51a8ff66;background:#51a8ff12}.perf8-grid{display:grid;grid-template-columns:1.08fr .92fr;gap:8px}.perf8-box{border:1px solid #1b293a;border-radius:11px;background:#080e16;padding:10px;overflow:hidden}.perf8-box h3{font-size:10px;margin:0 0 8px;text-transform:uppercase;letter-spacing:.45px;color:#93a7bf}.perf8-table{width:100%;border-collapse:collapse;font-size:9px}.perf8-table th,.perf8-table td{padding:7px 6px;border-bottom:1px solid #ffffff0b;text-align:right;white-space:nowrap}.perf8-table th:first-child,.perf8-table td:first-child{text-align:left}.perf8-table th{color:#71859d;font-size:8px}.perf8-outcomes{display:flex;flex-direction:column;gap:6px;max-height:245px;overflow:auto}.perf8-trade{display:grid;grid-template-columns:70px 56px 1fr auto;gap:7px;align-items:center;padding:7px;border:1px solid #172536;border-radius:8px;background:#070c13;font-size:9px}.perf8-trade .side.BUY{color:#32e38d}.perf8-trade .side.SELL{color:#ff6070}.perf8-note{margin-top:8px;padding:9px;border:1px solid #ffb74b28;background:#ffb74b07;border-radius:9px;color:#bca985;font-size:9px;line-height:1.5}.perf8-quality{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:9px;border:1px solid #1c2a3d;border-radius:9px;background:#070c13;margin-top:8px}.perf8-quality b{font-size:11px}.perf8-quality span{font-size:9px;color:#8295ad}@media(max-width:1300px){.perf8-kpis{grid-template-columns:repeat(4,1fr)}}@media(max-width:900px){.perf8-grid{grid-template-columns:1fr}.perf8-kpis{grid-template-columns:repeat(2,1fr)}}`;
  if(!document.getElementById('perf8Style')){const s=document.createElement('style');s.id='perf8Style';s.textContent=css;document.head.appendChild(s)}
  const $=id=>document.getElementById(id);let data=null,view='grade';
  function ensure(){if($('performanceV8'))return;const root=document.createElement('section');root.id='performanceV8';root.className='perf8';root.innerHTML=`<div class="perf8-head"><div><div class="perf8-title">ZENCORE PERFORMANCE ENGINE</div><div class="perf8-sub">Ukur kualiti signal sebenar • TP1 lawan SL • gred • stability • sesi • regime • data quality</div></div><span class="perf8-badge">AUTO TRADE OFF</span></div><div class="perf8-kpis"><div class="perf8-kpi"><span>Total Signal</span><b id="p8Total">—</b><small>BUY + SELL tepat</small></div><div class="perf8-kpi"><span>Resolved</span><b id="p8Resolved">—</b><small>TP1-first / SL-first</small></div><div class="perf8-kpi"><span>Win Rate TP1</span><b id="p8Win">—</b><small>TP1 sebelum SL</small></div><div class="perf8-kpi"><span>Expectancy</span><b id="p8Exp">—</b><small>benchmark ±1R</small></div><div class="perf8-kpi"><span>Profit Factor</span><b id="p8PF">—</b><small>benchmark TP1</small></div><div class="perf8-kpi"><span>TP3 Reach</span><b id="p8TP3">—</b><small>max target dicapai</small></div><div class="perf8-kpi"><span>Avg Max R</span><b id="p8MaxR">—</b><small>target maksimum</small></div><div class="perf8-kpi"><span>Max Drawdown</span><b id="p8DD">—</b><small>benchmark R</small></div></div><div class="perf8-quality"><div><b>Data Quality Pine</b><br><span id="p8QualitySub">Menunggu statistik payload...</span></div><b id="p8Quality">—</b></div><div class="perf8-tabs"><button class="perf8-tab active" data-view="grade">Ikut Gred</button><button class="perf8-tab" data-view="stability">Ikut Stability</button><button class="perf8-tab" data-view="session">Ikut Sesi</button><button class="perf8-tab" data-view="regime">Ikut Regime</button><button class="perf8-tab" data-view="side">BUY vs SELL</button></div><div class="perf8-grid"><div class="perf8-box"><h3 id="p8TableTitle">Prestasi Ikut Gred</h3><div id="p8Table"></div></div><div class="perf8-box"><h3>Signal & Outcome Terkini</h3><div id="p8Recent" class="perf8-outcomes"></div></div></div><div class="perf8-note"><b>Nota penting:</b> Performance Engine mengukur <b>kualiti signal</b>. Win = TP1 dicapai sebelum SL; loss = SL sebelum TP1. Ia bukan untung/rugi sebenar MT5.</div>`;const anchor=$('v7Pro')||document.querySelector('.v6-head');if(anchor)anchor.insertAdjacentElement('afterend',root);else document.querySelector('.wrap')?.appendChild(root);root.querySelectorAll('.perf8-tab').forEach(b=>b.addEventListener('click',()=>{root.querySelectorAll('.perf8-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;renderTable()}))}
  const pct=v=>Number.isFinite(+v)?`${(+v).toFixed(1)}%`:'—';const cls=v=>!Number.isFinite(+v)?'':+v>=60?'perf8-good':+v>=45?'perf8-warn':'perf8-bad';
  function rows(){if(!data)return[];return view==='grade'?data.byGrade:view==='stability'?data.byStability:view==='session'?data.bySession:view==='regime'?data.byRegime:data.bySide}
  function renderTable(){const el=$('p8Table');if(!el||!data)return;const title={grade:'Prestasi Ikut Gred',stability:'Prestasi Ikut Signal Stability',session:'Prestasi Ikut Sesi',regime:'Prestasi Ikut Market Regime',side:'Prestasi BUY vs SELL'}[view];$('p8TableTitle').textContent=title;const r=rows();el.innerHTML=r.length?`<table class="perf8-table"><thead><tr><th>Kumpulan</th><th>Signal</th><th>Resolved</th><th>Win Rate</th><th>Exp.</th><th>TP2</th><th>TP3</th></tr></thead><tbody>${r.map(x=>`<tr><td><b>${x.key}</b></td><td>${x.total}</td><td>${x.resolved}</td><td class="${cls(x.winRate)}">${pct(x.winRate)}</td><td>${Number.isFinite(+x.expectancy)?(+x.expectancy).toFixed(2)+'R':'—'}</td><td>${pct(x.tp2Rate)}</td><td>${pct(x.tp3Rate)}</td></tr>`).join('')}</tbody></table>`:'<div class="muted">Belum cukup signal untuk statistik kumpulan.</div>'}
  function renderRecent(){const el=$('p8Recent');if(!el||!data)return;const r=(data.recent||[]).slice(0,20);el.innerHTML=r.length?r.map(t=>{const out=t.ambiguous?'AMBIGUOUS':t.superseded?'SUPERSEDED':t.firstOutcome==='TP1'?'WIN TP1':t.firstOutcome==='SL'?'LOSS SL':t.tp3Hit?'TP3':t.tp2Hit?'TP2':t.tp1Hit?'TP1':'OPEN';return `<div class="perf8-trade"><span>${new Date(t.signalTime||t.receivedAt||Date.now()).toLocaleTimeString()}</span><b class="side ${t.side}">${t.side}</b><span>${t.symbol||'—'} • ${t.grade||'—'} • Stability ${Number.isFinite(+t.stabilityScore)?Math.round(+t.stabilityScore):'—'}</span><b>${out}</b></div>`}).join(''):'<div class="muted">Belum ada signal BUY/SELL tepat direkodkan.</div>'}
  function render(){ensure();if(!data)return;const s=data.summary||{},q=data.dataQuality||{};$('p8Total').textContent=s.total??'—';$('p8Resolved').textContent=s.resolved??'—';$('p8Win').textContent=pct(s.winRate);$('p8Win').className=cls(s.winRate);$('p8Exp').textContent=Number.isFinite(+s.expectancy)?`${(+s.expectancy).toFixed(2)}R`:'—';$('p8PF').textContent=s.profitFactorInfinite?'∞':Number.isFinite(+s.profitFactor)?(+s.profitFactor).toFixed(2):'—';$('p8TP3').textContent=pct(s.tp3Rate);$('p8MaxR').textContent=Number.isFinite(+s.avgMaxR)?`${(+s.avgMaxR).toFixed(2)}R`:'—';$('p8DD').textContent=Number.isFinite(+s.maxDrawdownR)?`${(+s.maxDrawdownR).toFixed(1)}R`:'—';$('p8Quality').textContent=Number.isFinite(+q.nativeRate)?`${(+q.nativeRate).toFixed(1)}% NATIVE`:'—';$('p8Quality').className=Number.isFinite(+q.nativeRate)&&+q.nativeRate>=95?'perf8-good':'perf8-warn';$('p8QualitySub').textContent=`Native ${q.nativePosts??0} • Recovered ${q.recoveredPosts??0} • DB ${q.database||'—'}`;renderTable();renderRecent()}
  async function refresh(){try{const r=await fetch('/api/performance',{cache:'no-store'});if(r.ok){data=await r.json();render()}}catch(_){}}
  function init(){ensure();refresh();setInterval(refresh,15000);try{const es=new EventSource('/events');es.addEventListener('performance',e=>{try{data=JSON.parse(e.data);render()}catch(_){}})}catch(_){}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,500));else setTimeout(init,500);
})();

(function(){
  'use strict';
  const q=id=>document.getElementById(id);const N=v=>{if(v===null||v===undefined||v===''||v==='null'||v==='NaN')return null;const x=Number(v);return Number.isFinite(x)?x:null};const U=v=>String(v||'').toUpperCase();const fmt=(v,d=3)=>N(v)==null?'—':N(v).toLocaleString(undefined,{maximumFractionDigits:d});
  const css=`.v11-manager{margin-top:8px;border:1px solid #29405b;background:linear-gradient(135deg,#091522,#07101a);border-radius:12px;padding:10px}.v11-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.v11-title{font-size:10px;font-weight:950;letter-spacing:.45px}.v11-badge{font-size:8px;font-weight:900;padding:5px 8px;border-radius:999px;border:1px solid #51a8ff55;color:#8ec8ff}.v11-grid{display:grid;grid-template-columns:1.25fr repeat(5,.72fr);gap:7px;margin-top:8px}.v11-card{border:1px solid #1f3044;background:#07101a;border-radius:9px;padding:8px;min-width:0}.v11-card span{display:block;font-size:7px;color:#738aa4;text-transform:uppercase;letter-spacing:.45px}.v11-card b{display:block;font-size:13px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v11-action{margin-top:8px;padding:10px;border-radius:9px;border:1px solid #51a8ff35;background:#51a8ff08;font-size:10px;line-height:1.5}.v11-action strong{font-size:12px}.v11-action.good{border-color:#32e38d44;background:#32e38d08}.v11-action.warn{border-color:#ffb74b44;background:#ffb74b08}.v11-action.bad{border-color:#ff607055;background:#ff60700a}.v11-progress{height:7px;background:#142033;border-radius:99px;overflow:hidden;margin-top:8px}.v11-progress i{display:block;height:100%;background:linear-gradient(90deg,#51a8ff,#32e38d);width:0;transition:width .3s ease}.v11-foot{margin-top:7px;font-size:8px;color:#8296ae;line-height:1.45}.v11-integrity{margin-top:7px;padding:8px;border-radius:8px;font-size:9px;border:1px solid #32e38d33;color:#9ed9b8;background:#32e38d06}.v11-integrity.bad{border-color:#ff607055;color:#ff9baa;background:#ff607009}.v11-integrity.warn{border-color:#ffb74b44;color:#e6c48b;background:#ffb74b08}.v11-active-trade .v10-shield{display:none!important}.v11-runner{margin-top:5px;color:#9eb2c9;font-size:9px}.v11-good{color:#32e38d!important}.v11-warn{color:#ffb74b!important}.v11-bad{color:#ff6070!important}.v11-blue{color:#51a8ff!important}@media(max-width:1200px){.v11-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:720px){.v11-grid{grid-template-columns:1fr 1fr}.v11-head{align-items:flex-start;flex-direction:column}}`;
  if(!q('v11Style')){const s=document.createElement('style');s.id='v11Style';s.textContent=css;document.head.appendChild(s)}
  let live=null,lastRunner='',lastRunnerAt=0;
  function ensure(){const host=q('v10Focus');if(!host)return false;if(q('v11Manager'))return true;const box=document.createElement('div');box.id='v11Manager';box.className='v11-manager';box.innerHTML=`<div class="v11-head"><div><div class="v11-title">ZENCORE V11 — POSITION MANAGER + ENTRY TIMING ENGINE</div><div class="v11-foot" style="margin-top:2px">Mode berubah automatik: sebelum entry = timing • posisi aktif = pengurusan trade.</div></div><span id="v11Mode" class="v11-badge">MENILAI</span></div><div class="v11-grid"><div class="v11-card"><span>Status Utama</span><b id="v11Status">—</b></div><div class="v11-card"><span>Posisi / Arah</span><b id="v11Side">—</b></div><div class="v11-card"><span>Current R</span><b id="v11R">—</b></div><div class="v11-card"><span>Target Seterusnya</span><b id="v11Next">—</b></div><div class="v11-card"><span>Jarak Target</span><b id="v11Dist">—</b></div><div class="v11-card"><span>Protection</span><b id="v11Protect">—</b></div></div><div class="v11-progress"><i id="v11Bar"></i></div><div id="v11Action" class="v11-action warn"><strong>Menunggu data live...</strong></div><div id="v11Integrity" class="v11-integrity warn">Trade Integrity Guard sedang menilai Entry / SL / TP.</div><div id="v11Runner" class="v11-runner"></div>`;host.appendChild(box);return true}
  function set(id,text,cls){const e=q(id);if(!e)return;e.textContent=text??'—';e.classList.remove('v11-good','v11-warn','v11-bad','v11-blue');if(cls)e.classList.add(cls)}
  function biasSide(d){const a=U(d?.action);if(/BUY|LONG/.test(a))return'BUY';if(/SELL|SHORT/.test(a))return'SELL';const g=N(d?.globalTrend);return g>0?'BUY':g<0?'SELL':'WAIT'}
  function positionSide(d){if(d?.tradeIsBuy===true||U(d?.tradeIsBuy)==='TRUE')return'BUY';if(d?.tradeIsBuy===false||U(d?.tradeIsBuy)==='FALSE')return'SELL';return biasSide(d)}
  function wordDir(v){const s=U(v);if(/BUY|BULL|LONG|UPTREND|BUYER/.test(s))return'BUY';if(/SELL|BEAR|SHORT|DOWNTREND|SELLER/.test(s))return'SELL';return'WAIT'}
  function geometry(d,side){const e=N(d?.entry),sl=N(d?.sl),t1=N(d?.tp1),t2=N(d?.tp2),t3=N(d?.tp3);if([e,sl,t1,t2,t3].some(v=>v==null))return{ok:false,reason:'Entry / SL / TP belum lengkap.'};if(side==='BUY'){const ok=sl<e&&e<t1&&t1<=t2&&t2<=t3;return{ok,reason:ok?'Struktur level BUY sah.':'BUY perlukan SL < Entry < TP1 < TP2 < TP3.'}}if(side==='SELL'){const ok=sl>e&&e>t1&&t1>=t2&&t2>=t3;return{ok,reason:ok?'Struktur level SELL sah.':'SELL perlukan SL > Entry > TP1 > TP2 > TP3.'}}return{ok:false,reason:'Arah posisi belum jelas.'}}
  function zoneState(d,side){const e=N(d?.entry),a=N(d?.atr),c=N(d?.close);if(e==null||a==null||c==null||a<=0)return{dist:null,atrDist:null,inZone:false,near:false,chase:false};const pct=(N(q('zonePct')?.value)||15)/100,lo=e-a*pct,hi=e+a*pct,inZone=c>=lo&&c<=hi,dist=c<lo?lo-c:c>hi?c-hi:0,near=!inZone&&dist<=a*.25,chase=side==='BUY'?c>hi+a*.45:side==='SELL'?c<lo-a*.45:false;return{lo,hi,dist,atrDist:dist/a,inZone,near,chase}}
  function adverse(d,side){const opp=side==='BUY'?'SELL':'BUY';return[['HEMA',wordDir(d?.hemaTrend)],['Momentum',wordDir(d?.momentum)],['Market Power',wordDir(d?.powerText)],['MTF',wordDir(d?.mtfOverall)]].filter(x=>x[1]===opp).map(x=>x[0])}
  function runnerText(){if(!lastRunner||Date.now()-lastRunnerAt>10*60*1000)return'';const m=lastRunner.match(/Status:\s*([^|]+)/i);if(m)return`Arahan Pine: ${m[1].trim()}`;if(/TAKE PARTIAL|CLOSE HALF|CLOSE SEPARUH/i.test(lastRunner))return'Arahan Pine: pertimbangkan partial close ikut plan.';return''}
  async function loadRunner(){try{const a=await fetch('/api/alerts',{cache:'no-store'}).then(r=>r.json());if(!Array.isArray(a))return;const x=[...a].reverse().find(v=>/ZENCORE TRAILING|TAKE PARTIAL|HOLD POSITION|CLOSE HALF|CLOSE SEPARUH/i.test(String(v?.message||'')));if(x){lastRunner=String(x.message||'');lastRunnerAt=N(x.time)||Date.now()}}catch(_){}}
  function updateTop(active,posSide,bias,status,msg){if(!active)return;const sig=q('v10Signal');if(sig){sig.textContent=`POSISI ${posSide} • BIAS ${bias}`;sig.style.color=posSide==='BUY'?'#32e38d':'#ff6070'}const dec=q('v10Decision');if(dec){dec.textContent=`URUS ${posSide} AKTIF`;dec.style.color='#51a8ff'}const sub=q('v10DecisionSub');if(sub)sub.textContent=posSide===bias?`Bias semasa masih selari dengan posisi ${posSide}. Fokus pada target, trailing dan invalidation.`:`PERHATIAN: posisi ${posSide} tetapi bias semasa ${bias}. Utamakan perlindungan risiko dan jangan tambah posisi.`;const coach=q('v10Coach');if(coach)coach.textContent=msg}
  function render(){if(!ensure()||!live)return;const d=live,active=d.tradeActive===true||U(d.tradeActive)==='TRUE',posSide=positionSide(d),bias=biasSide(d),g=geometry(d,posSide),e=N(d.entry),sl=N(d.sl),c=N(d.close),t1=N(d.tp1),t2=N(d.tp2),t3=N(d.tp3),risk=e!=null&&sl!=null?Math.abs(e-sl):null;document.body.classList.toggle('v11-active-trade',active);set('v11Mode',active?'POSITION MANAGEMENT':'ENTRY TIMING',active?'v11-blue':'v11-warn');set('v11Side',active?`${posSide} AKTIF`:`SETUP ${bias}`,posSide==='BUY'||(!active&&bias==='BUY')?'v11-good':posSide==='SELL'||(!active&&bias==='SELL')?'v11-bad':'v11-warn');
    if(active){if(!g.ok){set('v11Status','LEVEL MISMATCH','v11-bad');set('v11R','—');set('v11Next','—');set('v11Dist','—');set('v11Protect','STOP ANALISIS','v11-bad');q('v11Bar').style.width='0%';q('v11Action').className='v11-action bad';q('v11Action').innerHTML='<strong>JANGAN GUNA LEVEL INI.</strong> Arah posisi dan susunan Entry / SL / TP tidak sepadan.';q('v11Integrity').className='v11-integrity bad';q('v11Integrity').textContent=`⚠️ ${g.reason}`;q('v11Runner').textContent=runnerText();updateTop(true,posSide,bias,'LEVEL MISMATCH','Trade Integrity Guard mengesan level tidak konsisten. Jangan tambah posisi dan tunggu plan baharu.');return}
      const rNow=risk&&c!=null?(posSide==='BUY'?(c-e)/risk:(e-c)/risk):null,hit1=d.tp1Hit===true||U(d.tp1Hit)==='TRUE',hit2=d.tp2Hit===true||U(d.tp2Hit)==='TRUE',hit3=d.tp3Hit===true||U(d.tp3Hit)==='TRUE',hitSL=d.slHit===true||U(d.slHit)==='TRUE';let next=hit1?(hit2?(hit3?null:t3):t2):t1,nextName=hit1?(hit2?(hit3?'SELESAI':'TP3'):'TP2'):'TP1';const dist=next==null||c==null?null:Math.abs(next-c),adv=adverse(d,posSide);let status='HOLD PLAN',protect='KEKAL SL',tone='good',msg='Posisi masih aktif. Kekalkan plan asal; jangan tambah posisi di luar zon.';
      if(hitSL){status='INVALIDATED / SL';protect='EXIT MODE';tone='bad';msg='SL telah disentuh. Anggap setup selesai dan elakkan revenge trade.'}else if(hit3){status='TP3 COMPLETE';protect='TRADE COMPLETE';tone='good';msg='TP3 sudah dicapai. Trade lengkap; tunggu signal baharu sebelum re-entry.'}else if(hit2){status='RUNNER MODE';protect='PROTECT RUNNER';tone='good';msg='TP2 sudah dicapai. Lindungi baki posisi dengan trailing; jangan longgarkan SL.'}else if(hit1){status='PROTECT PROFIT';protect='BE / PARTIAL';tone='good';msg='TP1 sudah dicapai. Pertimbangkan partial dan breakeven jika selari dengan plan.'}else if(rNow!=null&&rNow<-.75){status='DEKAT INVALIDATION';protect='HORMATI SL';tone='bad';msg='Harga hampir invalidation. Jangan lebarkan SL atau average down.'}else if(bias!==posSide&&bias!=='WAIT'){status='BIAS BERCANGGAH';protect='DEFENSIVE';tone='warn';msg=`Posisi ${posSide} tetapi bias semasa ${bias}. Jangan tambah posisi; utamakan SL dan protection.`}else if(adv.length>=2){status='RISIKO MENINGKAT';protect='DEFENSIVE';tone='warn';msg=`${adv.join(' + ')} mula bercanggah. Fokus perlindungan risiko.`}else if(rNow!=null&&rNow>=.7){status='PROFIT BERKEMBANG';protect='JANGAN TAMBAH';tone='good';msg='Trade bergerak memihak. Fokus target / trailing; jangan kejar entry tambahan.'}
      set('v11Status',status,tone==='good'?'v11-good':tone==='bad'?'v11-bad':'v11-warn');set('v11R',rNow==null?'—':`${rNow>=0?'+':''}${rNow.toFixed(2)}R`,rNow!=null&&rNow>=0?'v11-good':'v11-bad');set('v11Next',nextName,nextName==='SELESAI'?'v11-good':'v11-blue');set('v11Dist',dist==null?'—':fmt(dist,3));set('v11Protect',protect,tone==='bad'?'v11-bad':tone==='warn'?'v11-warn':'v11-good');q('v11Bar').style.width=`${rNow==null?0:Math.max(0,Math.min(100,(rNow+1)/4*100))}%`;q('v11Action').className=`v11-action ${tone}`;q('v11Action').innerHTML=`<strong>${status}</strong> — ${msg}`;q('v11Integrity').className='v11-integrity';q('v11Integrity').textContent=`✓ Trade Integrity Guard: ${g.reason}`;q('v11Runner').textContent=runnerText();updateTop(true,posSide,bias,status,msg+(runnerText()?` ${runnerText()}`:''));
    }else{const side=bias,z=zoneState(d,side),exact=['BUY','SELL'].includes(U(d.action)),stab=parseInt(q('v7Stability')?.textContent)||0,ready=parseInt(q('v7Readiness')?.textContent)||0,rr=(()=>{if(e==null||sl==null||t3==null)return null;const r=Math.abs(e-sl);return r?Math.abs(t3-e)/r:null})();let status='TUNGGU SETUP',protect='NO ENTRY',tone='warn',msg='Tunggu arah, lokasi entry dan confirmation yang lebih jelas.';if(g.ok&&z.inZone&&exact&&stab>=60&&ready>=70&&rr!=null&&rr>=1.5){status=`ENTRY ${side} TIMING KUAT`;protect='RISK PLAN READY';tone='good';msg='Harga dalam zon, exact signal wujud dan timing mencukupi. Kekalkan risiko ikut plan.'}else if(z.chase){status='JANGAN KEJAR';protect='WAIT RESET';tone='bad';msg='Harga terlalu jauh daripada zon entry. Tunggu pullback atau setup baharu.'}else if(z.inZone){status='DALAM ZON — TUNGGU TRIGGER';protect='WAIT EXACT';tone='warn';msg=exact?'Harga dalam zon tetapi saringan timing belum cukup kuat.':'Harga dalam zon. Tunggu exact BUY/SELL dan confirmation.'}else if(z.near){status='HAMPIR ZON';protect='STANDBY';tone='warn';msg='Harga menghampiri zon entry. Bersedia tetapi jangan masuk sebelum trigger lengkap.'}else if(!g.ok){status='LEVEL PLAN TIDAK SAH';protect='NO ENTRY';tone='bad';msg='Susunan Entry / SL / TP tidak selari dengan arah setup.'}set('v11Status',status,tone==='good'?'v11-good':tone==='bad'?'v11-bad':'v11-warn');set('v11R','—');set('v11Next',exact?`EXACT ${U(d.action)}`:'TUNGGU BUY/SELL',exact?'v11-good':'v11-warn');set('v11Dist',z.dist==null?'—':`${fmt(z.dist,3)} (${z.atrDist.toFixed(2)} ATR)`);set('v11Protect',protect,tone==='bad'?'v11-bad':tone==='good'?'v11-good':'v11-warn');q('v11Bar').style.width=`${Math.max(0,Math.min(100,ready))}%`;q('v11Action').className=`v11-action ${tone}`;q('v11Action').innerHTML=`<strong>${status}</strong> — ${msg}`;q('v11Integrity').className=g.ok?'v11-integrity':'v11-integrity bad';q('v11Integrity').textContent=`${g.ok?'✓':'⚠️'} Entry Plan Integrity: ${g.reason}`;q('v11Runner').textContent=''}
    const h=document.querySelector('.brand h1');if(h)h.textContent='ZENCORE V11 — TRADER FOCUS + POSITION MANAGER';const ph=document.querySelector('.phase-pill');if(ph)ph.textContent='V11: POSITION MANAGER';
  }
  async function fetchLatest(){try{const r=await fetch('/api/latest',{cache:'no-store'});if(r.ok){const d=await r.json();if(d&&Object.keys(d).length){live=d;render()}}}catch(_){}}
  function startStream(){try{const es=new EventSource('/events');es.onmessage=e=>{try{const d=JSON.parse(e.data);if(d&&d.symbol){live=d;render()}}catch(_){}};es.onerror=()=>{};}catch(_){}}
  function init(){ensure();fetchLatest();loadRunner();startStream();setInterval(fetchLatest,5000);setInterval(loadRunner,7000);setInterval(render,1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1200));else setTimeout(init,1200);
})();